### ISSUE TITLE
how to manage articles?

### ISSUE THREAD

**Issue by DougMaster** [xuqingfeng/SimpleWiki#1]
Hi. What is the background CMS landing address?  thinks.

**Comment by xuqingfeng** [comment]
There is no badkground, just put your articles.md in the `wiki` folder and you are good to to. 

``` sh
--- SimpleWiki/wiki ‹master› » tree .
.
├── index.md
└── test
    └── test.md

1 directory, 2 files
```

**Comment by DougMaster** [comment]
ah...ok thinks xu

**Comment by xuqingfeng** [comment]
no problem
